//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employments
    {
        public int Employment_id { get; set; }
        public int Person_Id { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public string Assignments { get; set; }
    
        public virtual Persons Persons { get; set; }
    }
}
