//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Expertise
    {
        public int Person_id { get; set; }
        public int Expertise_id { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual Expertises Expertises { get; set; }
        public virtual Persons Persons { get; set; }
    }
}
